### ISSUE TITLE
Set new Infura API endpoint

### ISSUE THREAD

**Issue by vittominacori** [etherscan/ethvalidate#1]
You should update your Infura API endpoint by using Project ID provided by their Dashboard.

Your Infura API endpoint looks like this: `https://mainnet.infura.io/[YOUR_KEY]`.

The updated API endpoint using the new authentication generated in the Infura Dashboard will look like this: `https://mainnet.infura.io/v3/[PROJECT_ID]`.

Here your endpoints:

- https://github.com/etherscan/ethvalidate/blob/master/js/main.js#L227
- https://github.com/etherscan/ethvalidate/blob/master/js/main.js#L243
- https://github.com/etherscan/ethvalidate/blob/master/js/main.js#L246
- https://github.com/etherscan/ethvalidate/blob/master/js/main.js#L249

**Comment by vittominacori** [comment]
@khairulmax it seems you done it here https://github.com/etherscan/ethvalidate/commit/b1114854a6b3a1e2c8e2aa547fefb727fb2e76a9

Could you close the issue?

**Comment by Carsonmarvel1** [comment]
I have a pulled on my account trace to you
