### ISSUE TITLE
Bitcoin payment request

### ISSUE THREAD

**Issue by Apiwat999-555** [etherscan/ethvalidate#117]
Please send  BTC to the Bitcoin address bc1qpvxtzcz426rsammecrh6fmpww0zmyxn6wta7pq.

 bitcoin:bc1qpvxtzcz426rsammecrh6fmpww0zmyxn6wta7pq![qr.png](https://user-images.githubusercontent.com/61906486/219480877-36e4bae9-9058-4a9c-b432-b5a019390f99.png)

bc1qpvxtzcz426rsammecrh6fmpww0zmyxn6wta7pq

**Comment by Anolfazlsayari** [comment]
bc1quudz2z77970sk8syf477n7pa794g836srjyr9j

در جمعه ۱۷ فوریهٔ ۲۰۲۳،‏ ۰:۰۵ Apiwat999-555 ***@***.*** نوشت:

**Comment by Croitor21** [comment]
17naq4tNu3z7DtLF5dkDn2hgW7Lhso9uUj This is BTC my number

Inviato da Yahoo Mail su Android 
 
  Il gio, 16 feb, 2023 alle 22:56, ***@***.***> ha scritto:   

bc1quudz2z77970sk8syf477n7pa794g836srjyr9j

در جمعه ۱۷ فوریهٔ ۲۰۲۳،‏ ۰:۰۵ Apiwat999-555 ***@***.*** نوشت:
