### ISSUE TITLE
HOW TO USE ETH VALIDATE ON AN INFURA NODE

### ISSUE THREAD

**Issue by Dymesb** [etherscan/ethvalidate#14]
I searched everywhere on the internet but I couldn't find a tutorial that taught how to use ETH VALIDATE to check transactions on Infura nodes ....

**Comment by Nikki268** [comment]
> @https://github.com/etherscan/ethvalidate/issues/14#issue-716090535

**Comment by drumenbassik** [comment]
0x7CB5454213b5ffF7e60ad63768d77ea46E621b3A

**Comment by drumenbassik** [comment]
0x7CB5454213b5ffF7e60ad63768d77ea46E621b3A

**Comment by ImaDarrenya2** [comment]
Mmm???

**Comment by pablo7found** [comment]
chris

**Comment by nguyenducsang** [comment]
Ok

**Comment by pablo7found** [comment]
Validate

**Comment by nguyenducsang** [comment]
Fc

**Comment by kelvin488** [comment]
I
