### ISSUE TITLE
FinCrypChain Issue

### ISSUE THREAD

**Issue by BIGCRYPTO001** [etherscan/ethvalidate#4]
Help To Check Address Investor

**Comment by jclouise** [comment]
0x59a70e4a378119c6898fe48627a51b2aadc9b923

**Comment by BIGCRYPTO001** [comment]
@jclouise hello

**Comment by BIGCRYPTO001** [comment]
Can help  ne

**Comment by BIGCRYPTO001** [comment]
> 0x59a70e4a378119c6898fe48627a51b2aadc9b923

0xb7bBF6D2f5372022cc07B6677A9eB49ce78dA8c3

**Comment by BIGCRYPTO001** [comment]
@jclouise provide  my  dfrennce address


Address Ethereum
0x51acd1a86aa432370a81982f063c8b448b748f12

Contract address
0xb7bBF6D2f5372022cc07B6677A9eB49ce78dA8c3
