### ISSUE TITLE
Include account nonce on address lookup

### ISSUE THREAD

**Issue by 409H** [etherscan/ethvalidate#9]
It would be handy if `web3.eth.getTransactionCount()`/`nonce` was included in the lookup response so you can see if the account has been "active" on any network, even with an ETH balance of 0

**Comment by hungbui20384** [comment]
0x5D753160d4369C9FE41fEA5E0c5A823C8f81e303

**Comment by parsicoin98** [comment]
> این امر می تواند مفید اگر `web3.eth.getTransactionCount()`/ `nonce`در پاسخ مراجعه گنجانده شد، بنابراین شما می توانید ببینید اگر حساب "فعال" است در هر شبکه، حتی با یک تعادل ETH 0
0x9544cB184642e2767E2D865ac7Fb8732FCcD920C
MOHAMAD HASSANI

**Comment by parsicoin98** [comment]
If t helps you other than i have a couple of other address ether that
belong to the mine... Good day friends.

در تاریخ جمعه ۸ نوامبر ۲۰۱۹،‏ ۵:۳۷ mohamad hassani <notifications@github.com>
نوشت:

**Comment by parsicoin98** [comment]
for example ,those who agree to become a small or large group and rent a quine mine...that is ,by cooperating with the middle and weak strata,by aggregating small and medium power,and to the benefit of the weak and medium strata.
